### ISSUE TITLE
Deprecated: Benchpress.compileParse is deprecated, to be removed in v3.0.0

### ISSUE THREAD

**Issue by saesrpgmta** [yariplus/nodebb-widget-game-server-query#1]
As per the title.

Would you be able to update this to use compileRender instead please? Just so logs don't get spammed with that every time it refreshes the data or we lose support when v3 comes out.

Cheers!

**Comment by yariplus** [comment]
Yeah, definitely. Thanks for the heads up!

**Comment by saesrpgmta** [comment]
Thanks, dude, greatly appreciated!
